version: "3.8"
services:
  db:
    image: postgres:14.4
    container_name: gupy-teste-logica
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=321654987
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local